### ISSUE TITLE
Add global flag support

### ISSUE THREAD

**Issue by andrewjstone** [basho/clique#16]
We want to allow the user to dictate at runtime the type of output of the system. 

For instance, we want `--help` to always show help for the given command, but we don't want to make the user check whether the help command was run for each and every command.

We also will want to set the writer so that the values are output in a different manner. For example, we can use `--csv` to output in csv format instead of a human readable format for every command.

Having global flags will allow us to add different writers in the future.

**Comment by nickelization** [comment]
Fixed.
